version: "3"

services:
  web:
    image: corona
    container_name: covid-backend
    build: .
    command: gunicorn -b 0.0.0.0:5000 corona.wsgi:app
    env_file:
      - ./.flaskenv-prod
    volumes:
      - ./corona:/code/corona
      - ./migrations:/code/migrations

    ports:
      - "5000:5000"
    depends_on:
      - "db"

  db:
    image: postgres
    restart: always
    container_name: covid-database
    environment:
      POSTGRES_USER: coronadb
      POSTGRES_PASSWORD: coronadb
      POSTGRES_DB: coronadb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: database-manager
    restart: always
    ports:
      - 8001:8080
