version: "3"

services:
  web:
    image: qpcr-backend
    container_name: qpcr-backend
    build: .
    command: gunicorn -b 0.0.0.0:5000 qpcr_manager.wsgi:app
    env_file:
      - ./.flaskenv-prod
    volumes:
      - ./qpcr_manager:/code/qpcr_manager
      - ./migrations:/code/migrations

    ports:
      - "5000:5000"
    depends_on:
      - "db"

  db:
    image: postgres:12.3
    restart: always
    container_name: qpcr-database
    environment:
      POSTGRES_USER: qpcrdash
      POSTGRES_PASSWORD: qpcrpass
      POSTGRES_DB: qpcrdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.7.7
    container_name: qpcrdb-manager
    restart: always
    ports:
      - 8001:8080
